bookers/config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  get 'top' => 'homes#top'
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true
  
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
   @books = Book.all
   @book = Book.new

  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      flash[:alert] = "error"
      render :index
    end
  end

  def show
    @books = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to book_path(@book.id)
     flash[:notice] = "successfully"
    else
     @books = Book.all
     flash[:alert] = "errors"
     render :edit
    end
  end
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>

<% if @book.errors.any? %>
<div>
 <%= flash[:alert] %>
</div>
 <ul>
  <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  <% end %>
 </ul>
<% end %>

 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Body</h4>
 <%= f.text_area :body %>

 <%= f.submit 'Update Book' %>

<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to books_path do %><p>Back</p>
<% end %>

bookers/app/views/books/index.html.erb
<h1>Books</h1>
<table>
 <thead>
  <tr>
   <th>Title</th>
   <th>Body</th>
   <th colspan="3"></th>
  </tr>
 </thead>
 <tbody>
  <% @books.each do |book| %>
  <tr>
   <td><%= book.title %></td>
   <td><%= book.body %></td>
   <td><%= link_to "Show", book_path(book.id) %></td>
   <td><%= link_to "Edit", edit_book_path(book.id) %></td>
   <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
  <% end %>
 </tbody>
</table>
<%= form_with model: @book, url: '/books', method: :post do |f| %>

 <h2>New Book</h2>

 <% if @book.errors.any? %>
 <div>
  <%= flash[:alert] %>
 </div>
 <ul>
  <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  <% end %>
 </ul>
<% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>

 <h4>Book</h4>
 <%= f.text_area :body %>

 <%= f.submit 'Create Book' %>

<% end %>

bookers/app/views/books/show.html.erb
<% if flash[:notice] %>
 <div class="flash">
  <%= flash[:notice] %>
 </div>
<% end %>
<h4>Title</h4>

<p><%= @books.title %></p>

<h4>Body</h4>
<p><%= @books.body %></p>

<%= link_to "Edit", edit_book_path(@books.id) %>
<%= link_to books_path do %><p>Back</p>
<% end %>

bookers/app/views/homes/top.html.erb
<html>
 <body>
  <h1>ようこそBookersへ!</h1>
  <p>
   <strong>Bookers</strong>
    "では、さまざまな書類に関するあなたの意見や"
  </p>
  <p>印象を共有し交換することができます</p>

  <p>
   <a href="/books">start</a>
  </p>
 </body>
</html>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>